language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: nightly

before_install:
  - phpenv config-add tests/travis.ini

install:
  - composer require satooshi/php-coveralls --no-interaction

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS app;'

script:
  - phpunit --verbose --stderr --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls -v
